import { test, expect } from '@playwright/test';

test('shared rules, signup preserving draft, private collection, reload, delete and login', async ({ page }) => {
  const errors = []; page.on('pageerror', e => errors.push(e.message));
  await page.goto('/');
  await expect(page.getByText('$4.50', { exact: true })).toBeVisible();
  await page.getByRole('radio', { name: 'Iced', exact: true }).check();
  await expect(page.getByRole('radio', { name: 'Small', exact: true })).toBeDisabled();
  await expect(page.getByRole('radio', { name: 'Regular', exact: true })).toBeChecked();
  await expect(page.getByRole('radio', { name: 'Small', exact: true })).toHaveAccessibleDescription(/no room for ice/);
  await expect(page.getByRole('button', { name: 'Sign up to save' })).toBeEnabled();
  await page.getByRole('radio', { name: 'Hot', exact: true }).check();
  await expect(page.getByRole('radio', { name: 'Small', exact: true })).toBeEnabled();
  await page.getByRole('radio', { name: 'Small', exact: true }).check();
  await expect(page.getByRole('radio', { name: 'Iced', exact: true })).toBeDisabled();
  await page.getByRole('radio', { name: 'Large', exact: true }).check();
  await expect(page.getByRole('radio', { name: 'Iced', exact: true })).toBeEnabled();
  await page.getByRole('radio', { name: 'Iced', exact: true }).check();
  await page.getByRole('radio', { name: 'Oat', exact: true }).check();
  await expect(page.getByText('$6.50', { exact: true })).toBeVisible();
  await page.getByLabel('Give your favorite a name').fill('My afternoon oat');
  await page.getByRole('button', { name: 'Sign up to save' }).click();
  await page.getByLabel('Username', { exact: true }).fill('browser_barista');
  await page.getByLabel('Password', { exact: true }).fill('afternoon-oat-test-passphrase');
  await page.getByRole('button', { name: 'Create account', exact: false }).click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.getByLabel('Give your favorite a name')).toHaveValue('My afternoon oat');
  await expect(page.getByRole('radio', { name: 'Oat', exact: true })).toBeChecked();
  await page.getByRole('button', { name: 'Save recipe', exact: false }).click();
  await expect(page.getByRole('status').first()).toContainText('Recipe saved');
  await page.getByRole('link', { name: /Saved recipes/ }).click();
  await expect(page.getByRole('heading', { name: 'My afternoon oat' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('heading', { name: 'My afternoon oat' })).toBeVisible();
  expect(await page.evaluate(() => ({ cookie: document.cookie, local: localStorage.length, session: sessionStorage.length }))).toEqual({ cookie: '', local: 0, session: 0 });
  await page.getByRole('button', { name: 'Log out', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'My afternoon oat' })).not.toBeVisible();
  await page.getByRole('button', { name: 'Log in', exact: true }).first().click();
  await page.getByLabel('Username', { exact: true }).fill('BROWSER_BARISTA');
  await page.getByLabel('Password', { exact: true }).fill('afternoon-oat-test-passphrase');
  await page.getByRole('dialog').getByRole('button', { name: 'Log in', exact: false }).last().click();
  await expect(page.getByRole('dialog')).not.toBeVisible();
  await expect(page.getByRole('heading', { name: 'My afternoon oat' })).toBeVisible();
  await page.getByRole('button', { name: 'Delete My afternoon oat' }).click();
  await page.getByRole('button', { name: 'Delete recipe', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'My afternoon oat' })).not.toBeVisible();
  expect(errors).toEqual([]);
});

test('mobile layout, keyboard controls and Why Lean explanation', async ({ page }) => {
  await page.setViewportSize({ width: 390, height: 844 });
  await page.goto('/');
  await expect(page.getByRole('heading', { name: /A little ritual/ })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('radio', { name: 'Triple', exact: true }).check();
  await expect(page.getByRole('checkbox')).toBeDisabled();
  await expect(page.getByRole('checkbox')).not.toBeChecked();
  await expect(page.getByRole('checkbox')).toHaveAccessibleDescription(/Triple shots/);
  await page.getByRole('radio', { name: 'Double', exact: true }).check();
  await expect(page.getByRole('checkbox')).toBeEnabled();
  await page.getByRole('checkbox').check();
  await expect(page.getByRole('radio', { name: 'Triple', exact: true })).toBeDisabled();
  await expect(page.getByRole('radio', { name: 'Triple', exact: true })).toHaveAccessibleDescription(/Triple shots/);
  await page.getByRole('radio', { name: 'Double', exact: true }).focus();
  await page.keyboard.press('ArrowRight');
  await expect(page.getByRole('radio', { name: 'Single', exact: true })).toBeChecked();
  await expect(page.getByRole('alert')).toHaveCount(0);
  await page.getByRole('checkbox').uncheck();
  await expect(page.getByRole('radio', { name: 'Triple', exact: true })).toBeEnabled();
  await page.getByRole('link', { name: 'Why Lean', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Every cent accounted for' })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
