import { test, expect } from '@playwright/test';

test('Lean collection editor adds, edits, reorders, removes, and validates nested fields', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/?example=collections');
  const row = id => page.getByRole('article', { name: `Row ${id}`, exact: true });
  const validation = page.getByRole('list', { name: 'Validation errors' });
  await expect(page.getByRole('article')).toHaveCount(2);
  await row(1).getByRole('button', { name: 'Visited 0' }).click();
  await page.getByLabel('Title 1', { exact: true }).fill('Edited Alpha');
  await expect(page.getByLabel('Detail 1', { exact: true })).toHaveValue('First');
  await page.getByLabel('Title 1', { exact: true }).evaluate(input => { window.originalRowInput = input; });
  await page.getByRole('button', { name: 'Add row', exact: true }).click();
  await expect(page.getByRole('article')).toHaveCount(3);
  await expect(validation.getByRole('listitem')).toHaveText(['[2].title: required', '[2].detail: required']);
  await page.getByRole('button', { name: 'Save rows' }).click();
  await expect(page.getByRole('status')).toHaveText('Fix 2 fields');
  await expect(page.getByLabel('Title 3', { exact: true })).toHaveValue('');
  await page.getByRole('button', { name: 'Reverse rows' }).click();
  await expect(page.getByRole('article').first()).toHaveAccessibleName('Row 3');
  await expect(validation.getByRole('listitem')).toHaveText(['[0].title: required', '[0].detail: required']);
  await expect(row(1).getByRole('button', { name: 'Visited 1' })).toBeVisible();
  expect(await page.getByLabel('Title 1', { exact: true }).evaluate(input => input === window.originalRowInput)).toBe(true);
  await page.getByLabel('Title 1', { exact: true }).fill('Still Alpha');
  await expect(page.getByLabel('Title 2', { exact: true })).toHaveValue('Beta');
  await page.getByLabel('Title 3', { exact: true }).fill('Gamma');
  await page.getByLabel('Detail 3', { exact: true }).fill('Third');
  await expect(validation.getByRole('listitem')).toHaveCount(0);
  await page.getByLabel('Title 2', { exact: true }).fill('');
  await expect(validation.getByRole('listitem')).toHaveText(['[1].title: required']);
  await row(2).getByRole('button', { name: 'Remove row' }).click();
  await expect(validation.getByRole('listitem')).toHaveCount(0);
  await page.getByRole('button', { name: 'Save rows' }).click();
  await expect(page.getByRole('status')).toHaveText('Saved 2 rows');
  await page.getByRole('button', { name: 'Add row', exact: true }).click();
  await expect(row(4)).toBeVisible();
  await row(4).getByRole('button', { name: 'Remove row' }).click();
  await row(3).getByRole('button', { name: 'Remove row' }).click();
  await row(1).getByRole('button', { name: 'Remove row' }).click();
  await page.getByRole('button', { name: 'Save rows' }).click();
  await expect(page.getByRole('status')).toHaveText('Saved 0 rows');
  await page.getByRole('button', { name: 'Add row', exact: true }).click();
  await expect(row(5).getByRole('button', { name: 'Visited 0' })).toBeVisible();
  expect(errors).toEqual([]);
});

test('a provider and consumers in separately compiled libraries share context and retain state', async ({ page }) => {
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/?example=libraries');
  await expect(page.locator('.greeting')).toHaveText(['Provided: Hello, Lean', 'Default: Outside']);
  await page.getByRole('button', { name: 'Count 0' }).first().click();
  await page.getByLabel('Provider heading').fill('Updated');
  await expect(page.locator('.greeting')).toHaveText(['Updated: Hello, Lean', 'Default: Outside']);
  await expect(page.getByRole('button', { name: 'Count 1' })).toBeVisible();
  await expect(page.locator('#root')).toContainText('Other');
  expect(errors).toEqual([]);
});
