import LeanApp.Domain.Metadata
import Lean.Elab.Command

/-! # Checked representation adapters

A type whose constructor is private (so every value satisfies an invariant) can still be an
entity field, a `Domain` record field and an operation input or output. Declare how it is
represented and how a representation is checked:

```
structure Interval where
  private mk ::
  lo : Nat
  hi : Nat

def Interval.check (pair : Nat × Nat) : Option Interval := …   -- `none` unless lo ≤ hi

/-- An interval is stored and sent as its bounds, and read back through `Interval.check`. -/
represent Interval as Nat × Nat by Interval.toPair checked Interval.check
```

`represent T as R by enc checked dec` needs `Wire R`; `enc : T → R`, and `dec` is either
`R → Option T` or `R → Except String T`. It can be written in any module that sees `T`. It adds
exactly these declarations (see them with `#print`):

* `T.representation : Representation T R` — the encoder, the checker and the checker's name;
* `T.instHasTypeId` (only when `T` has no `HasTypeId` yet) — `T`'s wire name, package `domain`;
* `T.instWire : Wire T` — `Representation.codec`: encode with `enc` and `R`'s codec; decode
  with `R`'s codec, then the checker. A rejected value is the decode error
  `decode.invalid_representation` naming `T`, the checker and its reason, never a `T`;
* `T.instStorageCodec : StorageCodec T` — the same codec, so a stored value is re-checked when
  it is read (a stored value the checker rejects is a decode fault of the backend);
* `T.instFieldType : FieldType T` — a structured value with no form editor.

The schema is `R`'s schema under `T`'s own name. -/

namespace LeanApp.Domain
open Ontology

/-- How `T` is represented as `R`: a total encoder and a checker that accepts exactly the
`R`s that are valid `T`s. `checker` names the checking function in error messages. -/
structure Representation (T R : Type) where
  encode : T → R
  check : R → Except String T
  checker : String

/-- The two accepted checker shapes: `R → Option T` and `R → Except String T`. -/
class RepresentationCheck (R T : Type) (D : Type) where
  check : D → R → Except String T

instance : RepresentationCheck R T (R → Option T) where
  check decode raw := match decode raw with
    | some value => .ok value
    | none => .error "rejected"

instance : RepresentationCheck R T (R → Except String T) where
  check decode := decode

/-- `R`'s codec under `T`'s name; decoding runs the checker. -/
def Representation.codec [HasTypeId T] [Wire R] (rep : Representation T R) : Codec T where
  schema := .named (HasTypeId.typeId (α := T)) "1" (Wire.codec (α := R)).schema
  encode value := (Wire.codec (α := R)).encode (rep.encode value)
  decode json := do
    let raw ← (Wire.codec (α := R)).decode json
    match rep.check raw with
    | .ok value => pure value
    | .error reason =>
      Validation.fail "decode.invalid_representation" []
        [("type", (HasTypeId.typeId (α := T)).name), ("check", rep.checker), ("reason", reason)]

end LeanApp.Domain

namespace LeanApp.Domain.Represent
open Lean Elab Command

/-- `represent T as R by enc checked dec` (an identifier-led command, so `represent` stays an
ordinary name elsewhere). -/
syntax (name := representDecl) (docComment)? ident ident &"as" term " by " term:max &"checked" term:max : command

@[command_elab representDecl] def elabRepresent : CommandElab := fun stx => do
  unless stx[1].isIdent && stx[1].getId == `represent do throwUnsupportedSyntax
  let doc? := stx[0].getOptional?
  let target : Ident := ⟨stx[2]⟩
  let repr : Term := ⟨stx[4]⟩
  let encoder : Term := ⟨stx[6]⟩
  let checker : Term := ⟨stx[8]⟩
  let name ← liftCoreM <| realizeGlobalConstNoOverload target
  let info ← getConstInfo name
  unless info.type == .sort 1 && info.levelParams.isEmpty do
    throwErrorAt target "`represent` needs a type with no parameters; `{name}` has type {info.type}"
  let checkerName := (checker.raw.reprint.getD (toString checker.raw)).trimAscii.toString
  let typ := mkCIdent name
  let local_ (suffix : Lean.Name) := mkIdent (`_root_ ++ name ++ suffix)
  let hasTypeId ← liftTermElabM do
    return (← Meta.synthInstance? (mkApp (mkConst ``Ontology.HasTypeId [levelOne]) (mkConst name))).isSome
  elabCommand (← `(def $(local_ `representation) : LeanApp.Domain.Representation $typ $repr :=
    { encode := $encoder,
      check := LeanApp.Domain.RepresentationCheck.check (R := $repr) (T := $typ) $checker,
      checker := $(quote checkerName) }))
  let generated := s!"`{name}` is represented as `{(repr.raw.reprint.getD "").trimAscii}` (generated by `represent`)."
  let authored := match doc? with
    | some doc => (TSyntax.getDocString ⟨doc⟩).trimAscii.toString ++ "\n\n"
    | none => ""
  addDocStringCore (name ++ `representation) (authored ++ generated)
  unless hasTypeId do
    elabCommand (← `(instance $(local_ `instHasTypeId):ident : Ontology.HasTypeId $typ :=
      ⟨{ packageName := "domain", name := $(quote name.toString) }⟩))
  elabCommand (← `(instance $(local_ `instWire):ident : Ontology.Wire $typ :=
    ⟨LeanApp.Domain.Representation.codec $(local_ `representation)⟩))
  elabCommand (← `(instance $(local_ `instStorageCodec):ident : LeanApp.Domain.StorageCodec $typ :=
    ⟨LeanApp.Domain.Representation.codec $(local_ `representation)⟩))
  elabCommand (← `(instance $(local_ `instFieldType):ident : LeanApp.Domain.FieldType $typ :=
    ⟨.value, ⟨.none, false⟩⟩))

end LeanApp.Domain.Represent
