import Lean
import Lean.Compiler.LCNF.Types

open Lean Compiler LCNF
namespace LeanJS
namespace TypeScript

private def quote (s : String) : String := (Json.str s).compress
private def joined (ss : Array String) : String := String.intercalate ", " ss.toList

/-- Only describe a runtime layout we can establish; unknown is intentional. -/
private partial def valueType (t : Expr) (opaqueTypes : Array Name) (depth : Nat) : MetaM String := do
  if ← Meta.isProp t then return "null"
  if ← Meta.isTypeFormerType t then return "null"
  if depth == 0 then return "unknown"
  let t ← Meta.whnf t
  if t.isForall then
    return ← Meta.forallTelescope t fun ps result => do
      let args ← ps.mapIdxM fun i p => do
        return s!"a{i}: {← valueType (← Meta.inferType p) opaqueTypes (depth-1)}"
      return s!"({joined args}) => {← valueType result opaqueTypes (depth-1)}"
  let .const n us := t.getAppFn | return "unknown"
  let args := t.getAppArgs
  if opaqueTypes.contains n then return "unknown"
  if n == `Nat || n == `Int then return "bigint"
  if n == `String then return "string"
  if n == `Array then return s!"ReadonlyArray<{← valueType args[0]! opaqueTypes (depth-1)}>"
  if n == `List then return s!"LeanList<{← valueType args[0]! opaqueTypes (depth-1)}>"
  if n == `Option then return s!"LeanOption<{← valueType args[0]! opaqueTypes (depth-1)}>"
  let some (.inductInfo ind) := (← getEnv).find? n | return "unknown"
  if ind.ctors.isEmpty then return "never"
  let mut alts := #[]
  for ctor in ind.ctors do
    let .ctorInfo ci ← getConstInfo ctor | return "unknown"
    let mut ty ← Meta.inferType (mkConst ctor us)
    for i in [:ci.numParams] do
      let .forallE _ _ body _ := ty | return "unknown"
      let some param := args[i]? | return "unknown"
      ty := body.instantiate1 param
    let fields ← Meta.forallTelescope ty fun fields _ =>
      fields.mapM fun f => do valueType (← Meta.inferType f) opaqueTypes (depth-1)
    alts := alts.push s!"LeanCtor<{quote ctor.toString}, readonly [{joined fields}]>"
  return "(" ++ String.intercalate " | " alts.toList ++ ")"

private def header : String := "// Generated by LeanJS, ABI v0. Types/proofs occupy null argument/field slots.\n\
// Unknown marks a generic, host-specific, dependent, or depth-limited representation.\n\
export interface LeanCtor<Tag extends string = string, Fields extends readonly unknown[] = readonly unknown[]> {\n\
  readonly tag: Tag;\n\
  readonly fields: Fields;\n\
}\n\
export type LeanList<T> = LeanCtor<'List.nil', readonly []> | LeanCtor<'List.cons', readonly [T, LeanList<T>]>;\n\
export type LeanOption<T> = LeanCtor<'Option.none', readonly []> | LeanCtor<'Option.some', readonly [T]>;\n\
type LeanPartial<A extends unknown[], R, P extends unknown[] = []> =\n\
  A extends [infer H, ...infer T] ? ((...args: P) => LeanFunction<A, R>) & LeanPartial<T, R, [...P, H]> : unknown;\n\
export type LeanFunction<A extends unknown[], R> = { readonly leanArity: A['length'] } &\n\
  LeanPartial<A, R> & ((...args: A) => R);\n\
export interface LeanLibraryId { readonly packageName: string; readonly version: string; readonly moduleName: string }\n\
export interface LeanExportSignature { readonly name: string; readonly arity: number; readonly typeHash: string }\n\
export interface LeanLibraryInterface {\n\
  readonly id: LeanLibraryId; readonly abi: 'leanjs-v0'; readonly lean: '4.33.0';\n\
  readonly exports: readonly LeanExportSignature[];\n\
}\n\
export interface LeanManifest {\n\
  readonly abi: 'leanjs-v0';\n\
  readonly lean: '4.33.0';\n\
  readonly exports: readonly string[];\n\
  readonly library: LeanLibraryInterface | null;\n\
  readonly imports: readonly LeanLibraryInterface[];\n\
  readonly initialized: readonly string[];\n\
  readonly declarations: readonly { readonly name: string; readonly arity: number; readonly type: string; readonly intrinsic?: boolean; readonly builtin?: boolean; readonly constructor?: boolean; readonly parameters?: readonly string[]; readonly importedFrom?: LeanLibraryId }[];\n\
  readonly constructors: readonly { readonly name: string; readonly type: string; readonly parameters: number; readonly fields: number; readonly fieldInfo: readonly { readonly name: string; readonly type: string; readonly erased: boolean }[] }[];\n\
  readonly hookPlans: readonly { readonly name: string; readonly validation: 'fixed-hook-sequence-v1'; readonly sites: readonly { readonly primitive: string; readonly kind: string; readonly site: string }[] }[];\n\
}\n\
export declare const __leanjs: LeanManifest;\n\
export declare function __leanjs_fn<A extends unknown[], R>(arity: A['length'], body: (...args: A) => R): LeanFunction<A, R>;\n"

/-- Emit ESM declaration aliases using the actual retained argument-slot ABI.
Host-specific types are deliberately unknown, not native-reference structures. -/
def emit (exports : Array Name) (opaqueTypes : Array Name) : CoreM String := do
  let mut out := header
  for i in [:exports.size] do
    let name := exports[i]!
    let info ← getConstInfo name
    let ty ← Meta.MetaM.run' <| Meta.forallTelescopeReducing info.type fun ps result => do
      let params ← ps.mapM fun p => do valueType (← Meta.inferType p) opaqueTypes 7
      let result ← valueType result opaqueTypes 7
      if ps.isEmpty then return result
      return s!"LeanFunction<[{joined params}], {result}>"
    out := out ++ s!"declare const e{i}: {ty};\nexport \{ e{i} as {quote name.toString} };\n"
  return out
end TypeScript
end LeanJS
