// Generated by LeanContract.Generate from the public manifest. Do not edit; regenerate instead.
export type Option<T> = { tag: "none" } | { tag: "some"; value: T };
export type Result<T, E> = { readonly ok: true; readonly value: T } | { readonly ok: false; readonly error: E };
export interface Codec<T> { encode(value: T, path?: (string | number)[]): unknown; decode(value: unknown, path?: (string | number)[]): T }
export interface HttpOperation<Identity, Input, Output, Error> {
  readonly identity: Identity; readonly kind: "query" | "command"; readonly path: string;
  readonly maxBodyBytes: number | null; readonly describePolicy: string;
  readonly input: Codec<Input>; readonly output: Codec<Output>; readonly error: Codec<Error>;
  readonly encodeInput: (input: Input) => unknown; readonly decodeOutput: (value: unknown) => Output;
  readonly decodeError?: (value: unknown) => Error; readonly errorStatus?: (error: Error) => number;
}
export declare class CallFailure extends Error {
  readonly kind: "transport" | "protocol" | "decode" | "incompatible" | "unauthenticated" | "forbidden" | "cancelled";
  readonly code: string; readonly detail: unknown;
}
export interface CallOptions { readonly signal?: AbortSignal }
export interface ClientOptions { readonly baseURL?: string; readonly fetch?: typeof fetch; readonly verify?: boolean }
export interface ManifestOperation {
  readonly namespace: string; readonly name: string; readonly version: string; readonly kind: "query" | "command";
  readonly input: unknown; readonly output: unknown; readonly error: unknown;
  readonly http: { readonly path: string; readonly method: string; readonly maxBodyBytes: number | null };
  readonly metadata: { readonly title: string; readonly description: string; readonly describePolicy: string;
    readonly publish: { readonly topicField: string; readonly topicPrefix: string; readonly eventName: string; readonly alsoToActorField: string | null } | null;
    readonly issuesStreamTicket: boolean };
}
export interface Manifest { readonly operations: readonly ManifestOperation[] }
export type WireOperationId = leancontract_OperationId;
export type WireDecodeErrors = ontology_ValidationError[];

export type leancontract_OperationId = { "namespace": string; "name": string; "version": string };
export type ontology_PathSegment = { tag: "key"; value: string } | { tag: "index"; value: bigint } | { tag: "variant"; value: string } | { tag: "field"; value: { "package": string; "owner": string; "name": string } };
export type ontology_ValidationError = { "code": string; "path": ontology_PathSegment[]; "params": [string, string][] };

export type ListInput = null;
export type ListOutput = { "id": string; "name": string; "configuration": { "temperature": string; "size": string; "milk": string; "shots": string; "decaf": boolean }; "priceMinor": string }[];
export type ListError = never;
export type SaveInput = { "name": string; "configuration": { "temperature": string; "size": string; "milk": string; "shots": string; "decaf": boolean } };
export type SaveOutput = { "id": string; "name": string; "configuration": { "temperature": string; "size": string; "milk": string; "shots": string; "decaf": boolean }; "priceMinor": string };
export type SaveError = string;
export type DeleteInput = string;
export type DeleteOutput = null;
export type DeleteError = never;

export declare const types: Readonly<Record<string, Codec<unknown>>>;
export declare const manifestPath: string;
export declare const manifest: Manifest;
export declare const operations: {
  readonly list: HttpOperation<{ readonly namespace: "cafe"; readonly name: "list"; readonly version: "1" }, ListInput, ListOutput, ListError>;
  readonly save: HttpOperation<{ readonly namespace: "cafe"; readonly name: "save"; readonly version: "1" }, SaveInput, SaveOutput, SaveError>;
  readonly delete: HttpOperation<{ readonly namespace: "cafe"; readonly name: "delete"; readonly version: "1" }, DeleteInput, DeleteOutput, DeleteError>;
};
export interface Client {
  call(identity: { readonly namespace: "cafe"; readonly name: "list"; readonly version: "1" }, input: ListInput, options?: CallOptions): Promise<Result<ListOutput, ListError>>;
  call(identity: { readonly namespace: "cafe"; readonly name: "save"; readonly version: "1" }, input: SaveInput, options?: CallOptions): Promise<Result<SaveOutput, SaveError>>;
  call(identity: { readonly namespace: "cafe"; readonly name: "delete"; readonly version: "1" }, input: DeleteInput, options?: CallOptions): Promise<Result<DeleteOutput, DeleteError>>;
  readonly manifest: Manifest; readonly operations: typeof operations;
  verifyManifest(): Promise<void>;
}
export declare function createClient(options?: ClientOptions): Client;
export declare function decodeHttpReply<Identity, Input, Output, Error>(operation: HttpOperation<Identity, Input, Output, Error>, status: number, body: unknown): Result<Output, Error>;
export declare function canonical(value: unknown): string;
