// Generated by LeanContract.Generate from the public manifest. Do not edit; regenerate instead.
export type Option<T> = { tag: "none" } | { tag: "some"; value: T };
export type Result<T, E> = { readonly ok: true; readonly value: T } | { readonly ok: false; readonly error: E };
export interface Codec<T> { encode(value: T, path?: (string | number)[]): unknown; decode(value: unknown, path?: (string | number)[]): T }
export interface HttpOperation<Identity, Input, Output, Error> {
  readonly identity: Identity; readonly kind: "query" | "command"; readonly path: string;
  readonly maxBodyBytes: number | null; readonly describePolicy: string;
  readonly input: Codec<Input>; readonly output: Codec<Output>; readonly error: Codec<Error>;
  readonly encodeInput: (input: Input) => unknown; readonly decodeOutput: (value: unknown) => Output;
  readonly decodeError?: (value: unknown) => Error; readonly errorStatus?: (error: Error) => number;
}
export declare class CallFailure extends Error {
  readonly kind: "transport" | "protocol" | "decode" | "incompatible" | "unauthenticated" | "forbidden" | "cancelled";
  readonly code: string; readonly detail: unknown;
}
export interface CallOptions { readonly signal?: AbortSignal }
export interface ClientOptions { readonly baseURL?: string; readonly fetch?: typeof fetch; readonly verify?: boolean }
export interface ManifestOperation {
  readonly namespace: string; readonly name: string; readonly version: string; readonly kind: "query" | "command";
  readonly input: unknown; readonly output: unknown; readonly error: unknown;
  readonly http: { readonly path: string; readonly method: string; readonly maxBodyBytes: number | null };
  readonly metadata: { readonly title: string; readonly description: string; readonly describePolicy: string;
    readonly publish: { readonly topicField: string; readonly topicPrefix: string; readonly eventName: string; readonly alsoToActorField: string | null } | null;
    readonly issuesStreamTicket: boolean };
}
export interface Manifest { readonly operations: readonly ManifestOperation[] }
export type WireOperationId = leancontract_OperationId;
export type WireDecodeErrors = ontology_ValidationError[];

export type leanreact_tickets_Ticket = { "type": { "package": string; "name": string }; "scope": string; "key": string };
export type leanreact_tickets_Title = string;
export type leanreact_tickets_Status = string;
export type leanreact_tickets_User = { "type": { "package": string; "name": string }; "scope": string; "key": string };
export type leanreact_tickets_TicketValue = { "title": leanreact_tickets_Title; "status": leanreact_tickets_Status; "assignee": Option<leanreact_tickets_User> };
export type leanreact_tickets_TicketSummary = { "id": leanreact_tickets_Ticket; "revision": bigint; "value": leanreact_tickets_TicketValue };
export type leanreact_tickets_SaveTicket = { "id": leanreact_tickets_Ticket; "expectedRevision": bigint; "title": leanreact_tickets_Title; "status": leanreact_tickets_Status };
export type leanreact_tickets_SaveError = { tag: "notFound"; value: null } | { tag: "conflict"; value: leanreact_tickets_TicketSummary };
export type leancontract_OperationId = { "namespace": string; "name": string; "version": string };
export type ontology_PathSegment = { tag: "key"; value: string } | { tag: "index"; value: bigint } | { tag: "variant"; value: string } | { tag: "field"; value: { "package": string; "owner": string; "name": string } };
export type ontology_ValidationError = { "code": string; "path": ontology_PathSegment[]; "params": [string, string][] };

export type ListInput = null;
export type ListOutput = leanreact_tickets_TicketSummary[];
export type ListError = never;
export type SaveInput = leanreact_tickets_SaveTicket;
export type SaveOutput = leanreact_tickets_TicketSummary;
export type SaveError = leanreact_tickets_SaveError;

export declare const types: Readonly<Record<string, Codec<unknown>>>;
export declare const manifestPath: string;
export declare const manifest: Manifest;
export declare const operations: {
  readonly list: HttpOperation<{ readonly namespace: "leanreact.tickets"; readonly name: "list"; readonly version: "1" }, ListInput, ListOutput, ListError>;
  readonly save: HttpOperation<{ readonly namespace: "leanreact.tickets"; readonly name: "save"; readonly version: "1" }, SaveInput, SaveOutput, SaveError>;
};
export interface Client {
  call(identity: { readonly namespace: "leanreact.tickets"; readonly name: "list"; readonly version: "1" }, input: ListInput, options?: CallOptions): Promise<Result<ListOutput, ListError>>;
  call(identity: { readonly namespace: "leanreact.tickets"; readonly name: "save"; readonly version: "1" }, input: SaveInput, options?: CallOptions): Promise<Result<SaveOutput, SaveError>>;
  readonly manifest: Manifest; readonly operations: typeof operations;
  verifyManifest(): Promise<void>;
}
export declare function createClient(options?: ClientOptions): Client;
export declare function decodeHttpReply<Identity, Input, Output, Error>(operation: HttpOperation<Identity, Input, Output, Error>, status: number, body: unknown): Result<Output, Error>;
export declare function canonical(value: unknown): string;
