#!/usr/bin/env node
/** Scaffold a standalone LeanApp repo. Usage: node scripts/new-app.mjs --name demo --out ../demo */
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, '..');
const args = process.argv.slice(2);
const opt = (name, fallback) => {
  const i = args.indexOf(`--${name}`);
  return i >= 0 ? args[i + 1] : fallback;
};
const name = opt('name');
const out = opt('out');
if (!name || !out) {
  console.error('usage: node scripts/new-app.mjs --name <pkg> --namespace <ns> --out <dir>');
  process.exit(1);
}
const ns = opt('namespace', name);
const Name = name.replace(/(^|[-_])(\w)/g, (_, __, c) => c.toUpperCase());
const dest = resolve(out);

const files = {
  'lakefile.toml': `name = "${name}"\nversion = "0.1.0"\ndefaultTargets = ["${Name}"]\n\n[[lean_lib]]\nname = "${Name}"\n`,
  'lean-toolchain': await readFile(join(root, 'lean-toolchain'), 'utf8'),
  [`${Name}/Domain.lean`]: `namespace ${Name}\nstructure Title where\n  value : String\ndef Title.parse (s : String) : Except String Title :=\n  let t := s.trim\n  if t.isEmpty then .error "empty" else .ok ⟨t⟩\nend ${Name}\n`,
  [`${Name}/Contracts.lean`]: `import ${Name}.Domain\nnamespace ${Name}\n-- Add LeanContract operations here.\nend ${Name}\n`,
  'native/lakefile.lean': `import Lake\nopen Lake DSL\npackage ${name}_native\nrequire leanreact from git "https://github.com/theoriclabs/lean-react" @ "v0.2.0-rc.1"\nrequire leandb from git "https://github.com/theoriclabs/LeanDB" @ "v0.4.0"\nrequire leanhttp from git "https://github.com/theoriclabs/leanhttp" @ "v0.3.1"\nlean_lib ${Name}Native\nlean_exe ${name} where\n  root := \`Main\n`,
  'native/Main.lean': `def main : IO UInt32 := do\n  IO.println "${name} ready"\n  return 0\n`,
  'gateway/serve.mjs': `import { createGateway } from 'leanapp/gateway';\nawait createGateway({ name: '${Name}', port: 8080, origin: 'http://127.0.0.1:8080', development: true });\n`,
  'README.md': `# ${Name}\n\nGenerated by \`scripts/new-app.mjs\`.\n\n\`\`\`sh\nnpm ci\n(cd native && lake build)\nnpm test\n\`\`\`\n`,
};

await mkdir(dest, { recursive: true });
for (const [path, body] of Object.entries(files)) {
  const file = join(dest, path);
  await mkdir(dirname(file), { recursive: true });
  await writeFile(file, body);
}
console.log(`wrote ${dest} (${Object.keys(files).length} files, namespace ${ns})`);
