#!/usr/bin/env python3
"""Stage the Part 1 post's app (`partiful_v2/`) as a full-stack app workspace on this checkout.

The post's files are read, never edited. `Domain.lean`, `Views.lean` and `Main.lean` are copied
to `.lake/partiful-app/PartifulApp/` with the milestone 3 imports in place of the milestone 2
ones (nothing else changes; the modules are `PartifulApp.*` because LeanAPI's own staged api
already claims `Partiful.*` in this build graph), and the workspace gets the lakefile an app
repository would have:

* it requires `leanreact` by path (this checkout); LeanReact brings LeanAPI, LeanDB and
  leanontology, which are path dependencies on their sibling checkouts (DDD-LAPI-04 pins them);
* `partiful_server` is the authored Main; the target `partiful_browser` runs it once with
  `LEANAPP_EMIT_CLIENT`, stages the browser entry and runtime next to the LeanJS module that
  `app%` wrote, and bundles them with esbuild;
* `partiful` is the same Main and `needs` the bundle, so `lake exe partiful` builds the bundle
  as a dependency, then serves the pages and the api (DDD-LAPI-07);
* `partiful_unmigrated` is the Main without its `migrations` clause (the refusal check).

Usage: python3 scripts/stage-partiful.py [PARTIFUL_V2_DIR]
"""
import json
import re
import sys
from pathlib import Path

root = Path(__file__).resolve().parent.parent
code = root.parent
spec = Path(sys.argv[1] if len(sys.argv) > 1 else code / 'domain_driven_development/partiful_v2').resolve()
out = root / '.lake/partiful-app'
(out / 'PartifulApp').mkdir(parents=True, exist_ok=True)

def write(path, text):
    if not path.exists() or path.read_text() != text:
        path.write_text(text)

def replace_once(text, old, new, name):
    assert text.count(old) == 1, f'{name}: expected `{old.strip()}` once'
    return text.replace(old, new)

# The milestone 3 import lines (the only edits).
domain = (spec / 'Domain.lean').read_text()
domain = replace_once(domain, 'import LeanApp.Core\n', 'import LeanDb.Model\nimport LeanApi.Core\n', 'Domain.lean')
domain = replace_once(domain, 'open LeanApp.Core\n', 'open LeanDb.Model LeanApi.Core\n', 'Domain.lean')
views = (spec / 'Views.lean').read_text()
views = replace_once(views, 'import Partiful.Domain\n', 'import PartifulApp.Domain\n', 'Views.lean')
views = replace_once(views, 'open LeanApp.Core LeanReact\n', 'open LeanDb.Model LeanApi.Core LeanReact\n', 'Views.lean')
main = (spec / 'Main.lean').read_text()
main = replace_once(main, 'import LeanApiDomain.App\n', 'import LeanReact.Server\n', 'Main.lean')
main = replace_once(main, 'import Partiful.Views\n', 'import PartifulApp.Views\n', 'Main.lean')
main = replace_once(main, 'open LeanApp.Core\n', 'open LeanDb.Model LeanApi.Core\n', 'Main.lean')
assert 'def main (args : List String)' in main, 'partiful_v2/Main.lean must define main (args)'
app = re.search(r'^app% (\S+) where', main, re.M).group(1)
write(out / 'PartifulApp/Domain.lean', domain)
write(out / 'PartifulApp/Views.lean', views)
write(out / 'PartifulApp/Main.lean', main)
unmigrated, count = re.subn(r'\n  migrations := \[.*?\n  \]\n', '\n', main, flags=re.S)
assert count == 1, 'Main.lean: expected one multi-line `migrations := [...]` clause'
write(out / 'PartifulUnmigrated.lean', '/- Generated: Main.lean without its `migrations` clause. -/\n' + unmigrated)
write(out / 'PartifulLaunch.lean',
      '/- Generated: `lake exe partiful` runs the authored Main once the browser bundle is built. -/\nimport PartifulApp.Main\n')

q = lambda value: json.dumps(str(value))
leanreact = root
leanapi = code / 'leanapi'
runtime = sorted((leanreact / 'engine/runtime').glob('*.mjs'))
node_modules = leanreact / 'node_modules'
lakefile = f'''import Lake
open System Lake DSL

/-! Generated by leanreact/scripts/stage-partiful.py: the post's app, as an app repository's
lakefile would declare it. -/
package partiful

-- LeanReact brings LeanAPI, LeanDB and leanontology (path dependencies on the sibling
-- checkouts during development; DDD-LAPI-04 pins git revisions).
require leanreact from {q(leanreact)}

lean_lib PartifulApp

/-- The authored Main. The browser target runs it once to emit the client. -/
lean_exe partiful_server where
  root := `PartifulApp.Main

/-- The compiled browser bundle: the client emitted by the server binary, the LeanJS module
`app%` wrote, the browser entry and the runtime, bundled with esbuild. -/
target partiful_browser pkg : FilePath := do
  let some server ← findLeanExe? `partiful_server | error "partiful_server is not declared"
  let serverJob ← server.exe.fetch
  let entry : FilePath := {q(leanreact / 'engine/browser/App.mjs')}
  let runtime : Array FilePath := #[{', '.join(q(path) for path in runtime)}]
  let adapters : Array FilePath := #[{q(leanreact / 'engine/adapters/leanjs-react.mjs')}, {q(leanreact / 'engine/adapters/leanjs-contract.mjs')}]
  let contract : Array FilePath := #[{q(leanapi / 'LeanContract/Fetch.mjs')}, {q(leanapi / 'LeanContract/Codecs.mjs')}]
  let inputs ← (#[entry] ++ runtime ++ adapters ++ contract).mapM fun file => (inputTextFile file : SpawnM _)
  let out := pkg.dir / ".lake" / "leanreact-browser" / {q(app)}
  buildFileAfterDep (out / "app.mjs") (serverJob.add (Job.mixArray inputs)) fun exe => do
    IO.FS.createDirAll (out / "runtime")
    proc {{ cmd := exe.toString, cwd := pkg.dir, env := #[("LEANAPP_EMIT_CLIENT", some out.toString)] }}
    IO.FS.writeFile (out / "entry.mjs") (← IO.FS.readFile entry)
    for file in runtime ++ contract do
      IO.FS.writeFile (out / "runtime" / file.fileName.get!) (← IO.FS.readFile file)
    for file in adapters do
      -- One `Fetch.mjs` module identity once the runtime is staged side by side.
      let text := (← IO.FS.readFile file).replace "../../../leanapi/LeanContract/Fetch.mjs" "./Fetch.mjs"
      IO.FS.writeFile (out / "runtime" / file.fileName.get!) text
    proc {{
      cmd := {q(node_modules / '.bin/esbuild')}
      cwd := pkg.dir
      env := #[("NODE_PATH", some {q(node_modules)})]
      args := #[(out / "entry.mjs").toString, "--bundle", "--format=esm", "--platform=browser",
        "--target=es2022", "--define:process.env.NODE_ENV=\\"production\\"", s!"--outfile={{out / "app.mjs"}}"] }}

/-- `lake exe partiful [migrate [--check]]`: builds the bundle first, then gates the database
and serves the api and the pages. -/
lean_exe partiful where
  root := `PartifulLaunch
  needs := #[partiful_browser]

lean_exe partiful_unmigrated where
  root := `PartifulUnmigrated
'''
write(out / 'lakefile.lean', lakefile)
write(out / 'lean-toolchain', (root / 'lean-toolchain').read_text())
packages = [
    ('leanreact', leanreact, 'lakefile.toml', False),
    ('leanontology', code / 'leanontology', 'lakefile.toml', True),
    ('leandb', code / 'LeanDB', 'lakefile.toml', True),
    ('leanapi', code / 'leanapi', 'lakefile.toml', True),
    ('leansqlite', code / 'LeanDB/.lake/packages/leansqlite', 'lakefile.lean', True),
    ('leancrypto', code / 'leanapi/.lake/packages/leancrypto', 'lakefile.lean', True),
]
manifest = {'version': '1.2.0', 'packagesDir': '.lake/packages',
            'packages': [{'type': 'path', 'scope': '', 'name': name, 'manifestFile': 'lake-manifest.json',
                          'inherited': inherited, 'dir': str(path), 'configFile': config}
                         for name, path, config, inherited in packages],
            'name': 'partiful', 'lakeDir': '.lake', 'fixedToolchain': False}
write(out / 'lake-manifest.json', json.dumps(manifest, indent=1) + '\n')
print(out)
